name: CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - run: pip install flake8 pytest
    - name: Lint
      run: flake8 . --max-line-length=100
    - name: Test
      run: pytest -v
    - name: Build Docker image
      run: docker build -t devops-lab:ci .
  deploy:
    needs: build-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Debug
      run: echo "Provider length = ${#PROVIDER}, SA length = ${#SA}"
      env:
        PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        SA: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    - uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    - uses: google-github-actions/setup-gcloud@v2
    - run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev
    - run: |
        docker build -t asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/devops-lab-repo/web:${{ github.sha }} .
        docker push asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/devops-lab-repo/web:${{ github.sha }}
    - uses: google-github-actions/deploy-cloudrun@v3
      with:
        service: devops-lab
        region: asia-southeast1
        image: asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/devops-lab-repo/web:${{ github.sha }}